---
- name: Include tasks 'validate_ubuntu_lts_version.yml'
  include_tasks: validate_ubuntu_lts_version.yml
  when: ubuntu_pro_state == 'present' or ubuntu_pro_state == 'attached'

- name: Include tasks 'requirements.yml'
  include_tasks: requirements.yml
  when: ubuntu_pro_state == 'present' or ubuntu_pro_state == 'attached'

- name: Include tasks 'configure.yml'
  include_tasks: configure.yml
  when: ubuntu_pro_state == 'present' or ubuntu_pro_state == 'attached'

- name: Include tasks 'register.yml'
  include_tasks: register.yml
  when: ubuntu_pro_state == 'present' or ubuntu_pro_state == 'attached'

- name: Include tasks 'enable_services.yml'
  include_tasks: enable_services.yml
  when: ubuntu_pro_enabled_services is defined and (ubuntu_pro_state == 'present' or ubuntu_pro_state == 'attached')

- name: Include tasks 'disable_services.yml'
  include_tasks: disable_services.yml
  when: ubuntu_pro_disabled_services is defined and (ubuntu_pro_state == 'present' or ubuntu_pro_state == 'attached')

- name: Include tasks 'unregister.yml'
  include_tasks: unregister.yml
  when: ubuntu_pro_state == 'absent' or ubuntu_pro_state == 'detached'

- name: Include tasks 'uninstall.yml'
  include_tasks: uninstall.yml
  when: ubuntu_pro_state == 'absent'
